# Generated by Django 2.2.4 on 2019-09-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0003_auto_20190906_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdata',
            name='baseTag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fishdata',
            name='pitTag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fishdata',
            name='report',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='identify',
            name='pitTag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
